feat(casl): implement casl
easyBSB/easyBSB pull request #109
Opened 2022-05-15 01:20 UTC by r-hannuschka

- [ ] e2e tests

2022-05-15 06:42 UTC, konne requested changes

2022-05-15 06:42 UTC, konne commented on apps/server/src/app/auth/utils/jwt-auth.strategy.ts
> +    if (iat < exp) {
please use proper jwt check:
1. check if the signature valid
2. time is >= nbf (not before timestamp)
3. time is <= exp (expire timestamp)

iat is the issued at timestamp

2022-05-15 06:45 UTC, konne requested changes

2022-05-15 06:45 UTC, konne commented on apps/server/src/app/roles/constants/actions.ts
> +  Destroy = 'destroy',
please rename to delete

2022-05-15 06:45 UTC, konne commented on apps/server/src/app/roles/providers/ability.factory.ts
> +        can(Actions.Update, 'all')
not all, Write has only rights to write into the
Set Parameter Entpoints in connection, but for example not 
for changing the connection params,...

2022-05-15 06:45 UTC, konne commented on package.json
> +    "@casl/ability": "^5.4.3",
pin dependency

2022-05-16 01:28 UTC, r-hannuschka commented on apps/server/src/app/roles/constants/actions.ts
> +  Destroy = 'destroy',
done

2022-05-16 01:28 UTC, r-hannuschka commented on package.json
> +    "@casl/ability": "^5.4.3",
done

2022-05-16 10:39 UTC, konne approved these changes

2022-05-16 10:39 UTC, merged